version: '2.1'
services:
  db:
    restart: always
    image: "quay.io/debezium/example-postgres:1.9.1.Final"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/.document-store/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  documents:
    restart: always
    image: "document-store:latest"
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
